Parameters:
  abc:
    Description: abc
    Type: String
  DomainName:
    Description: Domain name for your website (example.com)
    Type: String
Resources:






###########

ApiMethod:
    Type: AWS::ApiGateway::Method
    Properties:
        AuthorizationType: NONE
        HttpMethod: ANY
        Integration:
            IntegrationHttpMethod: POST
            IntegrationResponses:
              - StatusCode: 200
                SelectionPattern: .*
            Type: AWS_PROXY
            Uri: !Sub "arn:aws:apigateway:${AWS::Region}:lambda:path/2015-03-31/functions/${LambdaFunction.Arn}/invocations"
        ResourceId: !Ref ApiResource
        RestApiId: !Ref RestApi
